# This file originally by FJN 3.12.2021

stages:
  - build
  - test

image: gcc

make_sim:
    stage: build
    rules:
      - if: $CI_COMMIT_BRANCH =~ $CI_DEFAULT_BRANCH
        when: never
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: manual
    before_script:
      - apt update && apt -y install cmake autoconf libblas-dev liblapack-dev
    script:
      - mkdir -p build; cd build
      - cmake --verbose -DMAKE_PLAY=OFF -DMAKE_TESTS=OFF ..
      - make sim report reader sieve
    artifacts:
      paths:
        - build/bin/sim
        - build/bin/sieve
        - build/bin/reader
        - build/bin/report
    cache:
      key: $CI_COMMIT_BRANCH
      paths:
        - build

make_play:
    stage: build
    rules:
      - if: $CI_COMMIT_BRANCH =~ $CI_DEFAULT_BRANCH
        when: never
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: manual
    before_script:
      - apt update && apt -y install cmake autoconf libblas-dev liblapack-dev mesa-common-dev libglew-dev freeglut3-dev
    script:
      - mkdir -p build; cd build
      - cmake -DMAKE_SIM=OFF -DMAKE_TOOLS=OFF ..
      - make play
    artifacts:
      paths:
        - build/bin/play
    cache:
      key: libglut-cache 
      paths:
        - /usr/lib/x86_64-linux-gnu/libglut*
      